[package]
name = "salt-bot"
version = "0.2.0"
authors = ["Ole <oksandum@gmail.com>"]
edition = "2018"


[dependencies]
serenity = "0.7.2"
rand = "0.7.3"
serde = "1.0.106"
serde_json = "1.0.52"
reqwest = { version = "0.10.4", features = ["json", "blocking"] }